<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('leads', function (Blueprint $table) {
            $table->id();

            // Idempotency key generated by the browser. The unique index is what
            // makes a retried submission return the existing lead instead of
            // creating a duplicate.
            // Not uuid(): the browser falls back to a `web-<ts>-<rand>` id when
            // crypto.randomUUID is unavailable, so this accepts both shapes.
            $table->string('submission_id', 64)->unique();
            $table->string('lead_code', 32)->unique();

            // Contact
            $table->string('name', 100);
            $table->string('whatsapp_number', 20);
            $table->string('whatsapp_normalized', 20);
            $table->string('domicile', 100);

            // Qualification answers
            $table->string('activity', 32);
            $table->string('goal', 32);
            $table->string('timeline', 32);
            $table->string('investment_readiness', 32);
            $table->string('program_interest', 32);

            // Provenance
            $table->string('source', 32)->default('website');
            $table->string('source_cta', 100);
            $table->timestamp('consent_at');

            // Attribution — flat columns so reporting can group without JSON
            // functions across MySQL/Postgres/SQLite.
            $table->text('landing_page')->nullable();
            $table->text('referrer')->nullable();
            $table->string('utm_source', 255)->nullable();
            $table->string('utm_medium', 255)->nullable();
            $table->string('utm_campaign', 255)->nullable();
            $table->string('utm_content', 255)->nullable();
            $table->string('utm_term', 255)->nullable();

            // Scoring — server-owned, never accepted from the client
            $table->unsignedSmallInteger('score')->default(0);
            $table->string('qualification', 32)->default('low_intent');
            $table->json('scoring_reasons')->nullable();
            $table->string('scoring_version', 32)->nullable();
            $table->timestamp('scored_at')->nullable();

            // Follow-up pipeline
            $table->string('status', 32)->default('new');
            $table->foreignId('assigned_consultant_id')->nullable()
                ->constrained('education_consultants')->nullOnDelete();
            $table->string('assignment_reason', 64)->nullable();
            $table->timestamp('assigned_at')->nullable();
            $table->timestamp('follow_up_due_at')->nullable();
            $table->timestamp('first_contacted_at')->nullable();
            $table->timestamp('last_contacted_at')->nullable();
            $table->timestamp('qualified_at')->nullable();
            $table->timestamp('converted_at')->nullable();
            $table->timestamp('lost_at')->nullable();
            $table->string('lost_reason', 128)->nullable();

            $table->timestamp('last_submitted_at')->nullable();
            $table->unsignedSmallInteger('submission_count')->default(1);

            $table->timestamps();
            $table->softDeletes();

            $table->index('whatsapp_normalized');
            $table->index('qualification');
            $table->index('status');
            $table->index('program_interest');
            $table->index('source_cta');
            $table->index('created_at');
            $table->index(['utm_source', 'utm_campaign']);
            $table->index(['status', 'follow_up_due_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('leads');
    }
};
